apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ocp-demo-xxyy-worker-us-west-2b
...
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-demo-rnh2q
      machine.openshift.io/cluster-api-machineset: ocp-demo-xxyy-worker-us-west-2b
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-demo-xxyy
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-demo-xxyy-worker-us-west-2b
    spec:
      metadata:
        creationTimestamp: null
      providerSpec:
      ...
          placement:
            availabilityZone: us-west-2b
            region: us-west-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m4.xlarge
          metadata:
            creationTimestamp: null
          publicIp: null
