---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-b38b-7ggrn
  name: cluster-b38b-7ggrn-additional-compute
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-b38b-7ggrn
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: cluster-b38b-7ggrn-worker-eu-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-b38b-7ggrn
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-b38b-7ggrn-worker-eu-central-1a
    spec:
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 100
              volumeSize: 22
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-b38b-7ggrn-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: eu-central-1a
            region: us-east-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-b38b-7ggrn-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-b38b-7ggrn-private-eu-central-1a
          tags:
          - name: kubernetes.io/cluster/cluster-b38b-7ggrn
            value: owned
          userDataSecret:
            name: worker-user-data
